Task2
VolhaZha/OzAutoCSharp pull request #2
Opened 2023-11-07 08:07 UTC by VolhaZha

Task 2

2023-11-08 11:12 UTC, IgorKheidorov requested changes
Exceptions

2023-11-08 11:12 UTC, IgorKheidorov commented on Order.cs
> +                string phoneString = value.ToString();
Magic numbers

2023-11-08 11:12 UTC, IgorKheidorov commented on Order.cs
> +    {
private const long PNONE_LENGTH = 13;

2023-11-08 11:12 UTC, IgorKheidorov commented on Order.cs
> +                if (phoneString.Length != 13)
if (phoneString.Length != PHONE_LENGTH)

2023-11-27 10:28 UTC, closed without merging

2023-11-27 10:28 UTC, VolhaZha commented
No need.